# Generated by Django 4.0.4 on 2022-04-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('loading', 'loading'), ('in WH', 'in WH'), ('loaded', 'loaded'), ('delivered', 'delivered'), ('delivering', 'delivering')], max_length=128),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('IDLE', 'idle'), ('DELIVERING', 'delivering'), ('TRAVELING', 'traveling'), ('ARRIVE WAREHOUSE', 'arrive warehouse'), ('LOADING', 'loading')], max_length=128),
        ),
    ]
