# Generated by Django 4.0.4 on 2022-04-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('loaded', 'loaded'), ('delivering', 'delivering'), ('loading', 'loading'), ('delivered', 'delivered'), ('in WH', 'in WH')], max_length=128),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('TRAVELING', 'traveling'), ('ARRIVE WAREHOUSE', 'arrive warehouse'), ('LOADING', 'loading'), ('DELIVERING', 'delivering'), ('IDLE', 'idle')], max_length=128),
        ),
    ]
