# Generated by Django 4.0.4 on 2022-04-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('loaded', 'loaded'), ('delivering', 'delivering'), ('loading', 'loading'), ('delivered', 'delivered')], max_length=128),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('traveling', 'traveling'), ('delivering', 'delivering'), ('arrive warehouse', 'arrive warehouse'), ('idle', 'idle'), ('loading', 'loading')], max_length=128),
        ),
    ]
